"""add_otp_fields_to_users

Revision ID: 0e0b7227e903
Revises: 44ab69b4bb1a
Create Date: 2026-09-26 12:34:58.587779

"""
from alembic import op
import sqlalchemy as sa


revision = '0e0b7227e903'
down_revision = '44ab69b4bb1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
